######################################################################
# Automatically generated by qmake (3.0) seg jul 4 13:50:44 2016
######################################################################

TEMPLATE = lib
#TARGET = siga-qt
INCLUDEPATH += . ../lib/json/include
CONFIG += c++11
Release:DESTDIR = build
Debug:DESTDIR = build

# Input
HEADERS += include/data-structures/btree.h \
           include/data-structures/sparse-matrix.h \
           include/data-structures/time-serie-tree.h \
           include/data-structures/time-serie-tree-formatter.h \
           include/data-structures/time-serie-tree-saver.h \
           include/utils/string-utils.h \
           include/utils/md5.h \
           include/utils/filesystem.h \
           include/converter/siga-converter.cpp \
           include/parsers/csv_parser.hpp \
           include/date/cdate.h \
           include/date/cdatecalc.h \
           include/date/ctime.h \
           include/date/ctimestamp.h \
           include/data-structures/tree-node.h

SOURCES += src/data-structures/time-serie-tree.cpp \
           src/data-structures/time-serie-tree-formatter.cpp \
           src/data-structures/time-serie-tree-saver.cpp \
           src/utils/string-utils.cpp \
           src/utils/md5.cpp \
           src/utils/filesystem.cpp \
           src/converter/siga-converter.cpp \
           src/parsers/csv_parser.cpp \
           src/date/cdate.cpp \
           src/date/cdatecalc.cpp \
           src/date/ctime.cpp \
           src/date/ctimestamp.cpp \           
           src/data-structures/tree-node.cpp
