######################################################################
# Automatically generated by qmake (3.0) seg jul 4 13:50:44 2016
######################################################################

TEMPLATE = app
TARGET = siga-qt
INCLUDEPATH += .
CONFIG += c++11
Release:DESTDIR = build

# Input
HEADERS += include/data-structures/tree.h \
           include/data-structures/sparse-matrix.h \
           include/data-structures/time-serie-tree.h \
           include/date/cdate.h \
           include/date/cdatecalc.h \
           include/date/ctime.h \
           include/date/ctimestamp.h \
           include/data-structures/tree-node.h

SOURCES += src/data-structures/time-serie-tree.cpp \
           src/date/cdate.cpp \
           src/date/cdatecalc.cpp \
           src/date/ctime.cpp \
           src/date/ctimestamp.cpp \           
           src/data-structures/tree-node.cpp

include(test.pro)
