######################################################################
# Automatically generated by qmake (3.0) ter jul 5 14:58:19 2016
######################################################################

TEMPLATE = app
TARGET = tree_test
INCLUDEPATH += lib/igloo

# Input
SOURCES += test/sparse-matrix-tests.cpp
