######################################################################
# Automatically generated by qmake (3.0) sex jul 8 15:21:01 2016
######################################################################

TEMPLATE = app
TARGET = tree-node
INCLUDEPATH += . ../../lib/igloo ../../include
LIBS += -L../../build -lsiga-qt

# Input
SOURCES += tree-node-tests.cpp
